### ISSUE TITLE
Link for the transifex in contributing.md goes to a 404 page.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [QwantResearch/qwantmaps#6]
Typo or not already public translation group ?

**Comment by nlehuby** [comment]
Thanks for your feedback :heart_decoration: 

Can you please confirm it has been fixed ?

**Comment by PoorPocketsMcNewHold** [comment]
Still the same issue, with https://www.transifex.com/qwant-1/qwant-maps/translate/

**Comment by nlehuby** [comment]
What about this one https://www.transifex.com/qwant-1/qwant-maps/ ?

**Comment by PoorPocketsMcNewHold** [comment]
This one seems to work. I can access to the main translation page. Closing this issue.

**Comment by nlehuby** [comment]
Thanks again, and sorry about that, it looks like I'm a noob transifex coordinator :stuck_out_tongue:

**Comment by nlehuby** [comment]
Thanks for the translations :heart: 
More will come in the next days, we have a lot of work in progress for now ;)
